### ISSUE TITLE
ImportError: cannot import name 'factor_dector' from 'geodetector' (C:\Anaconda\lib\site-packages\geodetector\__init__.py)

### ISSUE THREAD

**Issue by 1084465585** [djw-easy/GeoDetector#1]
引入geodetector库报错了
![image](https://github.com/djw-easy/GeoDetector/assets/51635975/4512c378-16d3-4b00-8ade-7d3f21f2ff4c)

**Comment by djw-easy** [comment]
看README的安装说明
